name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.11', os: ubuntu-22.04, tox: py311}
          - {name: Windows, python: '3.11', os: windows-2022, tox: py311}
          - {name: Mac, python: '3.11', os: macos-12, tox: py311}
          - {name: '3.12-dev', python: '3.12-dev', os: ubuntu-22.04, tox: py312}
          - {name: '3.10', python: '3.10', os: ubuntu-22.04, tox: py310}
          - {name: '3.9', python: '3.9', os: ubuntu-22.04, tox: py39}
          - {name: '3.8', python: '3.8', os: ubuntu-22.04, tox: py38}
          - {name: '3.7', python: '3.7', os: ubuntu-22.04, tox: py37}
          - {name: 'PyPy', python: 'pypy-3.9', os: ubuntu-22.04, tox: pypy39}
          - {name: 'Pallets Minimum Versions', python: '3.11', os: ubuntu-22.04, tox: py311-min}
          - {name: 'Pallets Development Versions', python: '3.7', os: ubuntu-22.04, tox: py37-dev}
          - {name: Typing, python: '3.11', os: ubuntu-22.04, tox: typing}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912
        with:
          python-version: ${{ matrix.python }}
          # cache: 'pip'
          # cache-dependency-path: 'requirements/*.txt'
      - name: update pip
        run: |
          pip install --index-url https://:2023-02-16T00:04:10.897261Z@time-machines-pypi.sealsecurity.io/ -U wheel
          pip install -U setuptools
          python -m pip install -U pip

      - name: cache mypy
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python }}|${{ hashFiles('setup.cfg') }}
        if: matrix.tox == 'typing'
      - name: tox
        env:
          PIP_INDEX_URL: https://:2023-02-16T00:04:10.897261Z@time-machines-pypi.sealsecurity.io/
        run: pip install tox
      - run: tox run -e ${{ matrix.tox }}
